### ISSUE TITLE
Faulty css on the invalid password error.

### ISSUE THREAD

**Issue by Tjoosten** [ghermans/suitecrm_laravel#15]
<img width="1127" alt="schermafbeelding 2015-09-30 om 14 03 21" src="https://cloud.githubusercontent.com/assets/5157609/10192359/13b9e3de-677c-11e5-9170-db157d2faf38.png">

**Comment by Tjoosten** [comment]
@ghermans can u wait fixing this bug? I'm converting the css to scss for elixlir

**Comment by ghermans** [comment]
@Tjoosten  sure, no problem
