### ISSUE TITLE
!important note in the css

### ISSUE THREAD

**Issue by Tjoosten** [ghermans/suitecrm_laravel#40]
Avoid using !important in properties. It is usually indicative of a misunderstanding of CSS specificity and can lead to brittle code.

Is it safe to just delete it? @ghermans

**Comment by ghermans** [comment]
@Tjoosten  Normally it should be safe to delete it.

**Comment by Tjoosten** [comment]
Alright and can i call u on skype?

**Comment by ghermans** [comment]
@Tjoosten i'm on my way from antwerp to my place, i will be available on skype around 14:30

**Comment by Tjoosten** [comment]
Alright

**Comment by Tjoosten** [comment]
Fixed in css and scss. This can be closed.
